services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: blinkmeet-frontend

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: blinkmeet-backend

    ports:
      - "5001:5001"

    env_file:
      - ./backend/.env

    environment:
      REDIS_URL: redis://redis:6379

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    image: mongo:8

    container_name: blinkmeet-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mongo_data:
